### ISSUE TITLE
"ReferenceError: s is not defined" when trying to use from a Meteor package

### ISSUE THREAD

**Issue by graemian** [epeli/underscore.string#419]
I'm trying to use underscore.string in my own package. My package.js has the line

api.use('underscorestring:underscore.string')

This results in "s" being available in the global context, but not in the package context. I don't see a

api.export("s");

in the underscore.string package.js, so I think "s" is getting exported in a hacky way, which results in underscore.string not playing nicely with the Meteor package compiler?

**Comment by stoeffel** [comment]
This will be in 3.1.0. I will publish a new version of underscore.string soon.

**Comment by splendido** [comment]
I've just published a new patch including this fix: `underscorestring:underscore.string@3.0.3_1`
See it also on atmosphere: https://atmospherejs.com/underscorestring/underscore.string

Thank you all, please excuse me for the stupid error.
Luca

**Comment by stoeffel** [comment]
Sweet, thanks so I don't have to hurry with 3.1.0

**Comment by brokenseal** [comment]
Hi guys,
I am currently using the latest version but I'm still having this problem, am I missing something?
This is my test package:

package.js
```
Package.describe({
	name: 'test',
	version: '0.0.1',
	summary: 'test',
	git: ''
});

Package.onUse(function(api) {
	api.use([
        'coffeescript'
    ]);
});

Package.onTest(function(api) {
	api.use([
        'coffeescript',
        'underscore',
        'underscorestring:underscore.string'
    ]);
	api.addFiles('tests/test.coffee', ['server']);
});
```

And this is my test file:
test.coffee
```
console.log("s", s)
```

And this is what I see in the console:
```
W20151203-14:27:03.428(1)? (STDERR) ReferenceError: s is not defined
W20151203-14:27:03.428(1)? (STDERR)     at Package (packages/local-test_test/tests/test.coffee:1:18)
```

Any idea?
